# Copyright 2022 susatthi All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

# アクション名
name: Setup Flutter

# アクションの説明
description: Setup Flutter

# 実行する内容を定義する
runs:

  # composit action の定義
  using: composite

  # ジョブの手順
  steps:

    # fvm のバージョンとチャネルを環境変数に設定する
    - name: Check fvm
      uses: kuhnroyal/flutter-fvm-config-action@v1

    # Flutter SDK の設定
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}
        cache: true
        cache-key: flutter
        cache-path: ${{ runner.tool_cache }}/flutter

    # flutter pub get を実行
    - name: Install Flutter dependencies
      run: flutter pub get

    # 環境変数ファイル（env.dart）を作成
    - name: Create env.dart
      run: bin/flutter_env -g ${{ secrets.ENV_GITHUB_ACCESS_TOKEN }}
