# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false

# see: https://github.com/rrousselGit/freezed/issues/488#issuecomment-894358980
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/l10n/*.dart'
  errors:
    invalid_annotation_target: ignore
