targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/src/entities/**/*.dart
            - lib/src/presentation/**/*state.dart
      json_serializable:
        generate_for:
          include:
            - lib/src/entities/**/*.dart
            - lib/src/presentation/**/*state.dart
