# Copyright 2022 Keyber Inc. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: github_search
description: Search Github repositories.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
