# Copyright 2022 Keyber Inc. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: Flutter CI

on:
  # プルリクエストが作成or更新された時
  pull_request:
    types:
      - opened
      - synchronize

  # main or develop ブランチに push された時
  push:
    branches:
      - main
      - develop
      - feature/29_ci # for debug

jobs:
  flutter_ci:
    name: Flutter CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      # ソースコードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # fvm を確認して Flutter バージョンとチャネルを環境変数に設定する
      - name: Check fvm
        uses: kuhnroyal/flutter-fvm-config-action@v1

      # Flutter SDK の設定
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      # flutter pub get を実行
      - name: Install Flutter dependencies
        run: flutter pub get

      # 環境変数ファイル（env.dart）を作成
      - name: Create env.dart
        run: |
          cat <<EOF > lib/config/env.dart
          ${{ secrets.ENV_DART }}
          EOF

      # 静的解析を実行
      - name: Run Flutter Analyze
        run: flutter analyze

      # テストを実行
      - name: Run Flutter Test
        run: flutter test --no-test-assets --coverage --coverage-path=~/coverage/lcov.info

      # Codecov に結果を送信
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ~/coverage/lcov.info
          flags: unittest,widgettest

      # Android Release Build
      - name: Build for Android
        run: flutter build appbundle -t lib/main.dart --release

      # Web Release Build
      - name: Build for Web
        run: flutter build web -t lib/main.dart --web-renderer html

  # Slack通知ジョブ
  notify_slack:
    name: Notify to Slack
    if: always()
    needs: flutter_ci
    runs-on: ubuntu-latest
    env:
      SLACK_CHANNEL: 個人開発_すさ_github_search
      SLACK_USERNAME: GitHub Actions
      SLACK_ICON: https://avatars.slack-edge.com/2020-11-25/1527503386626_319578f21381f9641cd8_512.png
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

      # テストに成功したとき
      - name: Succeed
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: SUCCEED
          SLACK_COLOR: good

      # テストに失敗したとき
      - name: Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: FAILURE
          SLACK_COLOR: danger
